'use strict';
const canvas=document.getElementById('game'),board=document.createElement('canvas');
board.width=600;board.height=450;
const arena=document.querySelector('.arena'),held=new Set(),modalPause=new WeakMap();
let bridge,ready=false,stopped=false,last=0,accumulator=0,messageTimer,blurPaused=false;
const $=id=>document.getElementById(id);
function present(){const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(board,0,0,canvas.width,canvas.height);}
function fitCanvas(){const {width,height}=arena.getBoundingClientRect(),scale=Math.max(.001,Math.min(width/600,height/450)),w=600*scale,h=450*scale,dpr=devicePixelRatio||1;canvas.style.width=w+'px';canvas.style.height=h+'px';const pw=Math.max(1,Math.round(w*dpr)),ph=Math.max(1,Math.round(h*dpr));if(canvas.width!==pw||canvas.height!==ph){canvas.width=pw;canvas.height=ph;}present();}
new ResizeObserver(fitCanvas).observe(arena);window.addEventListener('resize',fitCanvas);
function fail(e){stopped=true;$('error').hidden=false;$('error').textContent='游戏运行错误：'+e.message;console.error(e);}
function message(s){$('message').textContent=s;clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('message').textContent='',5000);}
function refresh(){const s=bridge.state();$('status').textContent=s.paused?'游戏暂停':`机会 ${s.lives}　得分 ${s.score}　炸弹 ${s.bombs}/${s.capacity}　核武器 ${s.nukes}`;$('level').textContent=`第 ${s.level} 关 · ${s.progress}%`;$('pause').textContent=s.paused?'继续 F3':'暂停 F3';$('sound').textContent=bridge.cpu.read(bridge.game+0x264)?'音效 F5':'音效关闭 F5';$('load').disabled=!bridge.files.has('ship233.mine');if(bridge.notice){message(bridge.notice);bridge.notice='';}}
function action(fn){if(!ready)return;try{fn();refresh();present();}catch(e){fail(e);}}
function down(key){action(()=>{if(key===113){stopped=false;last=0;accumulator=0;$('error').hidden=true;}bridge.keyDown(key);if(key===113&&bridge.state().paused)bridge.keyDown(114);if(key===116&&!bridge.cpu.read(bridge.game+0x264))bridge.stopAudio();});}
function up(key){if(ready)try{bridge.keyUp(key);}catch(e){fail(e);}}
function releaseKeys(){for(const key of held)up(key);held.clear();}
function enableAudio(){if(ready)bridge.audioReady().catch(()=>{});}
function openDialog(id){if(!ready||document.querySelector('dialog[open]'))return;releaseKeys();const dlg=$(id),running=!bridge.state().paused;modalPause.set(dlg,running);if(running)down(114);dlg.showModal();}
for(const dlg of document.querySelectorAll('dialog'))dlg.addEventListener('close',()=>{if(modalPause.get(dlg)&&bridge.state().paused)down(114);modalPause.delete(dlg);last=0;accumulator=0;canvas.focus();});
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
$('start').onclick=()=>{down(113);enableAudio();canvas.focus();};$('pause').onclick=()=>{releaseKeys();down(114);canvas.focus();};$('sound').onclick=()=>{down(116);enableAudio();canvas.focus();};$('help').onclick=()=>openDialog('instructions');$('closeHelp').onclick=()=>$('instructions').close();$('quit').onclick=()=>action(()=>{releaseKeys();if(bridge.state().paused)bridge.keyDown(114);bridge.end();});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('app').requestFullscreen();canvas.focus();}catch{message('此浏览器暂不支持全屏');}};
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'退出全屏':'全屏';fitCanvas();});
$('save').onclick=()=>action(()=>{const bytes=bridge.save();message(bytes?'存档已保存到此浏览器':'暂时无法存档');});$('load').onclick=()=>action(()=>{if(bridge.load()){stopped=false;last=0;accumulator=0;message('已读取存档');}else message('还没有存档');});
const keyNames={13:'Enter',32:'Space',37:'←',38:'↑',39:'→',40:'↓'};
function keyName(k){return keyNames[k]||(k>=112&&k<=123?'F'+(k-111):String.fromCharCode(k));}
function colorHex(v){return '#'+[v&255,(v>>>8)&255,(v>>>16)&255].map(x=>x.toString(16).padStart(2,'0')).join('');}
function colorValue(s){const v=parseInt(s.slice(1),16);return ((v&255)<<16)|(v&0xff00)|(v>>>16);}
for(let i=1;i<=21;i++)$('startLevel').add(new Option('第 '+i+' 关',i));
for(let i=0;i<10;i++)$('speed').add(new Option(`速度 ${i+1} · ${i*20+1} 毫秒${i===0?'（最快）':i===9?'（最慢）':''}`,i*20+1));
$('settings').onclick=()=>{if(!ready)return;const c=bridge.cpu,G=bridge.game;$('startLevel').value=c.read(G+0x268)+1;$('speed').value=c.read(G+0x308);$('useMouse').checked=!!c.read(G+0x30c);$('playerName').value=bridge.playerName||'Player';for(const f of document.querySelectorAll('[data-offset]')){f.dataset.key=c.read(G+(+f.dataset.offset));f.value=keyName(+f.dataset.key);}for(const f of document.querySelectorAll('[data-color]'))f.value=colorHex(c.read(G+(+f.dataset.color)));openDialog('options');};
for(const f of document.querySelectorAll('[data-offset]'))f.onkeydown=e=>{if(e.key==='Tab')return;e.preventDefault();if(e.key==='Escape')return;const key=e.keyCode;if((key<16&&key!==13)||key>=112){message('请选择方向键、空格、Enter、字母或数字键');return;}f.dataset.key=key;f.value=keyName(key);};
function applySettings(){const c=bridge.cpu,G=bridge.game,keys=[...document.querySelectorAll('[data-offset]')].map(f=>+f.dataset.key);if(new Set(keys).size!==keys.length){message('各操作的键位不能重复');return false;}c.write(G+0x308,+$('speed').value);c.write(G+0x30c,+$('useMouse').checked);bridge.playerName=$('playerName').value.trim().slice(0,12)||'Player';const config={speed:c.read(G+0x308),mouse:c.read(G+0x30c),name:bridge.playerName,keys:{},colors:{}};for(const f of document.querySelectorAll('[data-offset]')){c.write(G+(+f.dataset.offset),+f.dataset.key);config.keys[f.dataset.offset]=+f.dataset.key;}for(const f of document.querySelectorAll('[data-color]')){const val=colorValue(f.value);c.write(G+(+f.dataset.color),val);config.colors[f.dataset.color]=val;}c.run(0x40c18a,G);c.run(0x40c51d,G);try{localStorage.setItem('ship233-settings',JSON.stringify(config));}catch{}return true;}
$('applySettings').onclick=()=>action(()=>{if(applySettings()){$('options').close();message('设置已应用');}});
$('startSelected').onclick=()=>action(()=>{if(!applySettings())return;bridge.startLevel(+$('startLevel').value);if(bridge.state().paused)bridge.keyDown(114);stopped=false;last=0;accumulator=0;modalPause.set($('options'),false);$('options').close();});
function showScores(){const c=bridge.cpu,rows=$('scoreRows');rows.replaceChildren();const base=c.read(bridge.game+0x3a4);for(let i=0;i<10;i++){const a=base+i*44,tr=document.createElement('tr');for(const value of [i+1,bridge.str(a+4),c.read(a+24),c.read(a+20),c.read(a+28),bridge.str(a+32)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}rows.append(tr);}openDialog('heroes');}
$('scores').onclick=()=>action(showScores);
$('exportSave').onclick=()=>action(()=>{const bytes=bridge.save();if(!bytes)return;const url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download='ship233.mine';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('已导出存档');});
$('importSave').onclick=()=>$('saveFile').click();$('saveFile').onchange=async()=>{const f=$('saveFile').files[0];if(!f)return;const bytes=new Uint8Array(await f.arrayBuffer()),text=new TextDecoder().decode(bytes);if(bytes.length!==2109||!/^231[0-9A-F]+$/.test(text)){message('请导入原版 V2.33 格式的 .mine 存档');$('saveFile').value='';return;}action(()=>{bridge.files.set('ship233.mine',bytes);bridge.load();modalPause.set($('options'),false);$('options').close();stopped=false;message('存档已导入');});$('saveFile').value='';};
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;const k=e.keyCode;if(e.ctrlKey){const id={83:'save',76:'load'}[k];if(id){e.preventDefault();$(id).click();return;}if(k===77){e.preventDefault();action(()=>bridge.cpu.run(0x40ea98,bridge.game));return;}}if(e.altKey&&k>=48&&k<=57){e.preventDefault();action(()=>bridge.speed(0x8013+(k===48?9:k-49)));return;}const id={112:'help',115:'settings',117:'settings',118:'settings',119:'fullscreen',120:'scores',27:'quit'}[k];if(id){e.preventDefault();if(!e.repeat)$(id).click();return;}if(e.ctrlKey||e.altKey||e.metaKey)return;if([13,32,37,38,39,40,113,114,116].includes(k))e.preventDefault();if([113,114,116].includes(k)&&e.repeat)return;held.add(k);down(k);enableAudio();});
document.addEventListener('keyup',e=>{held.delete(e.keyCode);up(e.keyCode);});
window.addEventListener('blur',()=>{releaseKeys();blurPaused=ready&&!bridge.state().paused&&!document.querySelector('dialog[open]');if(blurPaused)down(114);last=0;accumulator=0;});window.addEventListener('focus',()=>{if(blurPaused&&bridge.state().paused)down(114);blurPaused=false;last=0;accumulator=0;});
for(const b of document.querySelectorAll('[data-key]')){let repeat,key;const offset={37:0x26c,39:0x270,90:0x274,32:0x278,88:0x27c,38:0x280,13:0x304};b.onpointerdown=e=>{e.preventDefault();if(!ready)return;b.setPointerCapture(e.pointerId);key=bridge.cpu.read(bridge.game+offset[+b.dataset.key]);held.add(key);down(key);if([32,90,88,38].includes(+b.dataset.key))repeat=setInterval(()=>down(key),150);enableAudio();};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{clearInterval(repeat);if(key!==undefined){held.delete(key);up(key);key=undefined;}};}
function pointer(e,click=false,right=false){if(!ready||document.querySelector('dialog[open]'))return;const r=canvas.getBoundingClientRect();action(()=>bridge.mouse((e.clientX-r.left)*600/r.width,(e.clientY-r.top)*450/r.height,click,right));if(click)enableAudio();}
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse')pointer(e);});canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus();pointer(e,true,e.button===2);});canvas.addEventListener('contextmenu',e=>e.preventDefault());
function loop(t){if(ready&&!stopped){accumulator+=last?Math.min(t-last,120):0;try{let updated=false,steps=0;while(accumulator>=bridge.state().step&&steps++<24){const step=bridge.state().step;bridge.frame();accumulator-=step;updated=true;}if(steps>=24)accumulator=0;if(updated)present();refresh();if(bridge.showScores){bridge.showScores=false;showScores();}}catch(e){fail(e);}}last=t;requestAnimationFrame(loop);}
(async()=>{try{const images={};await Promise.all(SHIP_RESOURCES.images.map(id=>new Promise((res,rej)=>{const im=new Image();im.onload=()=>{images[id]=im;res();};im.onerror=()=>rej(Error('无法载入图片 '+id));im.src=SHIP_RESOURCES.data[id];})));bridge=new ShipBridge(new ShipCPU(SHIP_MACHINE),board,images);window.ship=bridge;bridge.initialize();try{const cfg=JSON.parse(localStorage.getItem('ship233-settings')||'null');if(cfg){bridge.playerName=cfg.name;bridge.cpu.write(bridge.game+0x308,cfg.speed);bridge.cpu.write(bridge.game+0x30c,cfg.mouse);for(const [offset,v] of Object.entries({...cfg.keys,...cfg.colors}))bridge.cpu.write(bridge.game+(+offset),v);bridge.cpu.run(0x40c18a,bridge.game);bridge.cpu.run(0x40c51d,bridge.game);}}catch{}ready=true;window.gameReady=true;fitCanvas();refresh();requestAnimationFrame(loop);}catch(e){fail(e);}})();
